name: CloverGraves
version: '${version}'
main: com.slyph.clovergraves.AxGraves
api-version: '1.16'
authors: [slyph]
folia-supported: true
softdepend: [Vault]

permissions:
  axgraves.help:
    default: true
  axgraves.reload:
    default: op
  axgraves.list:
    default: true
  axgraves.list.other:
    default: op
  axgraves.tp:
    default: true
  axgraves.tp.bypass:
    default: op
  axgraves.allowgraves:
    default: true
  axgraves.limit.1:
    default: false
  axgraves.admin:
    default: op
  axgraves.update-notify:
    default: op
  axgraves.protection.bypass:
    default: op
  axgraves.history:
    default: op
  axgraves.restore:
    default: op
