package com.slyph.clovergraves.storage;

import com.slyph.clovergraves.utils.CloverLogger;
import org.jetbrains.annotations.NotNull;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public class SqlGraveStorage implements GraveStorage {
    @FunctionalInterface
    interface ConnectionFactory {
        Connection open() throws SQLException;
    }

    private final JdbcConfig config;
    private final ConnectionFactory connectionFactory;
    private final String tablePrefix;
    private final boolean historyEnabled;
    private final int keepPerPlayer;
    private final int keepDays;

    public SqlGraveStorage(@NotNull JdbcConfig config, boolean historyEnabled, int keepPerPlayer, int keepDays) {
        this(config, config::open, historyEnabled, keepPerPlayer, keepDays);
    }

    SqlGraveStorage(@NotNull JdbcConfig config, @NotNull ConnectionFactory connectionFactory,
                    boolean historyEnabled, int keepPerPlayer, int keepDays) {
        if (!config.tablePrefix().matches("[A-Za-z0-9_]*")) {
            throw new IllegalArgumentException("storage.table-prefix may contain only letters, numbers and underscores");
        }
        this.config = config;
        this.connectionFactory = connectionFactory;
        this.tablePrefix = config.tablePrefix();
        this.historyEnabled = historyEnabled;
        this.keepPerPlayer = Math.max(0, keepPerPlayer);
        this.keepDays = Math.max(0, keepDays);
    }

    private String graves() {
        return tablePrefix + "graves";
    }

    private String history() {
        return tablePrefix + "grave_history";
    }

    @Override
    public void init() {
        String id = switch (config.type()) {
            case H2 -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            case SQLITE -> "INTEGER PRIMARY KEY AUTOINCREMENT";
            case MYSQL -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
        };
        String blob = config.type() == JdbcConfig.Type.MYSQL ? "LONGBLOB" : "BLOB";

        try (Connection c = open(); Statement st = c.createStatement()) {
            st.executeUpdate("CREATE TABLE IF NOT EXISTS " + graves() + " (" +
                    "id " + id + "," +
                    "owner VARCHAR(36) NOT NULL," +
                    "owner_name VARCHAR(64)," +
                    "location VARCHAR(512) NOT NULL," +
                    "items " + blob + "," +
                    "data_version INT," +
                    "stored_xp INT NOT NULL DEFAULT 0," +
                    "created_at BIGINT NOT NULL)");

            st.executeUpdate("CREATE TABLE IF NOT EXISTS " + history() + " (" +
                    "id " + id + "," +
                    "owner VARCHAR(36) NOT NULL," +
                    "owner_name VARCHAR(64)," +
                    "location VARCHAR(512) NOT NULL," +
                    "items " + blob + "," +
                    "data_version INT," +
                    "stored_xp INT NOT NULL DEFAULT 0," +
                    "created_at BIGINT NOT NULL," +
                    "end_reason VARCHAR(32) NOT NULL," +
                    "ended_at BIGINT NOT NULL," +
                    "restored BOOLEAN NOT NULL DEFAULT FALSE)");

            createHistoryIndex(st);
        } catch (SQLException ex) {
            throw new IllegalStateException("failed to initialize grave storage schema", ex);
        }
    }

    private void createHistoryIndex(Statement statement) throws SQLException {
        String index = tablePrefix + "grave_history_owner_idx";
        String sql = "CREATE INDEX " + (config.type() == JdbcConfig.Type.MYSQL ? "" : "IF NOT EXISTS ")
                + index + " ON " + history() + " (owner, ended_at DESC)";
        try {
            statement.executeUpdate(sql);
        } catch (SQLException ex) {
            if (config.type() != JdbcConfig.Type.MYSQL) throw ex;
        }
    }

    @Override
    @NotNull
    public List<GraveRecord> loadAll() {
        List<GraveRecord> result = new ArrayList<>();
        String sql = "SELECT id, owner, owner_name, location, items, data_version, stored_xp, created_at FROM " + graves();

        try (Connection c = open(); PreparedStatement ps = c.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) result.add(readLiveRecord(rs));
        } catch (SQLException ex) {
            CloverLogger.error("failed to load graves from the database", ex);
        }
        return result;
    }

    @Override
    public long save(@NotNull GraveRecord record) {
        if (record.id() > 0) {
            String sql = "UPDATE " + graves() + " SET owner=?, owner_name=?, location=?, items=?, data_version=?, stored_xp=?, created_at=? WHERE id=?";
            try (Connection c = open(); PreparedStatement ps = c.prepareStatement(sql)) {
                bindGrave(ps, record);
                ps.setLong(8, record.id());
                if (ps.executeUpdate() > 0) return record.id();
            } catch (SQLException ex) {
                CloverLogger.error("failed to update a grave in the database", ex);
                return record.id();
            }
        }

        String sql = "INSERT INTO " + graves() + " (owner, owner_name, location, items, data_version, stored_xp, created_at) VALUES (?,?,?,?,?,?,?)";
        try (Connection c = open(); PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            bindGrave(ps, record);
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) return keys.getLong(1);
            }
        } catch (SQLException ex) {
            CloverLogger.error("failed to insert a grave into the database", ex);
        }
        return record.id();
    }

    private void bindGrave(@NotNull PreparedStatement ps, @NotNull GraveRecord record) throws SQLException {
        ps.setString(1, record.owner().toString());
        ps.setString(2, record.ownerName());
        ps.setString(3, record.location());
        ps.setBytes(4, record.items());
        ps.setInt(5, record.dataVersion());
        ps.setInt(6, record.storedXP());
        ps.setLong(7, record.createdAt());
    }

    @Override
    public void remove(long id, @NotNull EndReason reason) {
        try (Connection c = open()) {
            c.setAutoCommit(false);
            try {
                UUID owner = archiveAndDelete(c, id, reason);
                if (historyEnabled && owner != null) pruneHistory(c, owner);
                c.commit();
            } catch (SQLException ex) {
                c.rollback();
                throw ex;
            } finally {
                c.setAutoCommit(true);
            }
        } catch (SQLException ex) {
            CloverLogger.error("failed to remove/archive grave {} in the database", id, ex);
        }
    }

    private UUID archiveAndDelete(@NotNull Connection c, long id, @NotNull EndReason reason) throws SQLException {
        UUID owner = null;
        if (historyEnabled) {
            String select = "SELECT owner, owner_name, location, items, data_version, stored_xp, created_at FROM " + graves() + " WHERE id=?";
            try (PreparedStatement ps = c.prepareStatement(select)) {
                ps.setLong(1, id);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        owner = UUID.fromString(rs.getString("owner"));
                        String insert = "INSERT INTO " + history() + " (owner, owner_name, location, items, data_version, stored_xp, created_at, end_reason, ended_at, restored) VALUES (?,?,?,?,?,?,?,?,?,FALSE)";
                        try (PreparedStatement hist = c.prepareStatement(insert)) {
                            hist.setString(1, rs.getString("owner"));
                            hist.setString(2, rs.getString("owner_name"));
                            hist.setString(3, rs.getString("location"));
                            hist.setBytes(4, rs.getBytes("items"));
                            hist.setInt(5, rs.getInt("data_version"));
                            hist.setInt(6, rs.getInt("stored_xp"));
                            hist.setLong(7, rs.getLong("created_at"));
                            hist.setString(8, reason.name());
                            hist.setLong(9, System.currentTimeMillis());
                            hist.executeUpdate();
                        }
                    }
                }
            }
        }

        try (PreparedStatement ps = c.prepareStatement("DELETE FROM " + graves() + " WHERE id=?")) {
            ps.setLong(1, id);
            ps.executeUpdate();
        }
        return owner;
    }

    private void pruneHistory(@NotNull Connection c, @NotNull UUID owner) throws SQLException {
        if (keepDays > 0) {
            long cutoff = System.currentTimeMillis() - keepDays * 86_400_000L;
            try (PreparedStatement ps = c.prepareStatement("DELETE FROM " + history() + " WHERE ended_at < ?")) {
                ps.setLong(1, cutoff);
                ps.executeUpdate();
            }
        }

        if (keepPerPlayer > 0) {
            String sql = "DELETE FROM " + history() + " WHERE owner = ? AND id NOT IN (" +
                    "SELECT id FROM (SELECT id FROM " + history() + " WHERE owner = ? ORDER BY ended_at DESC LIMIT ?) keep_ids)";
            try (PreparedStatement ps = c.prepareStatement(sql)) {
                ps.setString(1, owner.toString());
                ps.setString(2, owner.toString());
                ps.setInt(3, keepPerPlayer);
                ps.executeUpdate();
            }
        }
    }

    @Override
    @NotNull
    public List<GraveRecord> history(@NotNull UUID owner, int limit) {
        List<GraveRecord> result = new ArrayList<>();
        if (!historyEnabled) return result;

        String sql = "SELECT id, owner, owner_name, location, items, data_version, stored_xp, created_at, end_reason, ended_at, restored FROM "
                + history() + " WHERE owner=? ORDER BY ended_at DESC LIMIT ?";
        try (Connection c = open(); PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, owner.toString());
            ps.setInt(2, Math.max(1, limit));
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) result.add(readHistoryRecord(rs));
            }
        } catch (SQLException ex) {
            CloverLogger.error("failed to load grave history for {}", owner, ex);
        }
        return result;
    }

    @Override
    @NotNull
    public Optional<GraveRecord> historyEntry(long historyId) {
        if (!historyEnabled) return Optional.empty();

        String sql = "SELECT id, owner, owner_name, location, items, data_version, stored_xp, created_at, end_reason, ended_at, restored FROM "
                + history() + " WHERE id=?";
        try (Connection c = open(); PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setLong(1, historyId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(readHistoryRecord(rs));
            }
        } catch (SQLException ex) {
            CloverLogger.error("failed to load grave history entry {}", historyId, ex);
        }
        return Optional.empty();
    }

    @Override
    public boolean claimForRestore(long historyId) {
        if (!historyEnabled) return false;
        String sql = "UPDATE " + history() + " SET restored = TRUE WHERE id = ? AND restored = FALSE";
        try (Connection c = open(); PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setLong(1, historyId);
            return ps.executeUpdate() > 0;
        } catch (SQLException ex) {
            CloverLogger.error("failed to claim grave history entry {} for restore", historyId, ex);
            return false;
        }
    }

    @Override
    public void close() {
    }

    private Connection open() throws SQLException {
        return connectionFactory.open();
    }

    @NotNull
    private GraveRecord readLiveRecord(@NotNull ResultSet rs) throws SQLException {
        return new GraveRecord(
                rs.getLong("id"), UUID.fromString(rs.getString("owner")), rs.getString("owner_name"),
                rs.getString("location"), rs.getBytes("items"), rs.getInt("data_version"),
                rs.getInt("stored_xp"), rs.getLong("created_at"), null, null
        );
    }

    @NotNull
    private GraveRecord readHistoryRecord(@NotNull ResultSet rs) throws SQLException {
        EndReason reason;
        try {
            reason = EndReason.valueOf(rs.getString("end_reason"));
        } catch (IllegalArgumentException ex) {
            reason = EndReason.REMOVED;
        }

        return new GraveRecord(
                rs.getLong("id"), UUID.fromString(rs.getString("owner")), rs.getString("owner_name"),
                rs.getString("location"), rs.getBytes("items"), rs.getInt("data_version"),
                rs.getInt("stored_xp"), rs.getLong("created_at"), reason,
                rs.getLong("ended_at"), rs.getBoolean("restored")
        );
    }
}
